[package]
name = "use_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
codee = { workspace = true, features = ["json_serde"] }
console_error_panic_hook = "0.1"
console_log = "1"
leptos = { workspace = true, features = [
    "nightly",
    "csr",
] }
leptos-use = { path = "../..", features = ["storage", "docs"] }
log = "0.4"
serde = "1.0.163"
web-sys = "0.3"

[dev-dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-test = { workspace = true }
